feat: release year and genreId filter
AAsadova34/java-filmorate pull request #10
Opened 2022-11-22 18:22 UTC by DanielSJavaDev

2022-11-22 18:47 UTC, AAsadova34 commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +            top = getTheBestFilms(limit).stream()
Модификатор доступа метода getTheBestFilms(int count) теперь можно изменить на private. 
Ну и меня вечно гоняют за private методы, расположенные выше public методов.

2022-11-23 04:50 UTC, AAsadova34 approved these changes
С логикой все ок, комментарий скорее косметический.

2022-11-23 10:03 UTC, DanielSJavaDev commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +            top = getTheBestFilms(limit).stream()
Поправил модификатор :)

2022-11-23 10:50 UTC, AlexandrShusharin requested changes
Основной вопрос по использованию метода getTheBestFilms(limit)

2022-11-23 10:50 UTC, AlexandrShusharin commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +                    .collect(Collectors.toList());
А нас не покарают на итоговом ревью, что выборка делается через stream, а не через SQL запрос. Чисто теоретически, если представить, что у нас огромная база, то это не логично сначала выгружать все фильмы, а потом начинать их парсить по критериям. Проще сразу выгрузить по заданным критериям.

2022-11-23 10:50 UTC, AlexandrShusharin commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +            top = getTheBestFilms(limit).stream()
Если getTheBestFilms(limit) возвращает ограниченное количество фильмов (например 10), то код будет работать не правильно на больших числах. Например, получили 10 наиболее популярных фильмов но среди них нет ни одного нашего жанра. В итоге мы вернем пустой список. Но в базе есть фильмы нашего жанра, но не входящие в ТОП-10 и мы должны вернуть 10 этих фильмов в соотвествие с их популярностью, даже если она нулевая.

2022-11-23 11:24 UTC, DanielSJavaDev commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +            top = getTheBestFilms(limit).stream()
Замечание резонное и я изначально написал отдельный эндпоинт и новые методы в сервисе с sql запросами на получение фильмов по жанру и году, но... когда начал проверять логику и пытаться запустить тесты, оказалось, что всё намного проще и нужно доработать уже существующий эндпоинт двумя параметрами. По тз нужно именно добавить фильтрацию топ 10 фильмов по жанру и году:

Фильтрация должна быть по двум параметрам. 
1. По жанру. 
2. За указанный год.

Итог такой, что нам не нужно доставать из базы фильмы по жанру и году, а нужно отфильтровать топ 10 по этим двум параметрам и если в топ 10 не будет нужного жанра или года, то список должен быть пустым.

2022-11-23 11:27 UTC, DanielSJavaDev commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +                    .collect(Collectors.toList());
Топ 10 так и останется топ 10, просто отфильтрованный по жанрам или году. Постман тесты так же проверяют, что список пустой, если нужного жанра или года в топ 10 не оказалось.

2022-11-23 11:46 UTC, AlexandrShusharin commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +            top = getTheBestFilms(limit).stream()
"Возвращает список самых популярных фильмов указанного жанра за нужный год"
Смотри, может я превратно понимаю логику задания. Но как мне кажется:
 **по заданию** - получить n самых популярных фильмов за определенный год и определенного жанра.
**в текущей реализации** - мы получаем фильмы за определенный год и определенного жанра из первых n самых популярных фильмов.
Грубо, если есть фильм отвечающий критериям по году и жанру в ТОП-10 (например на 3 позиции), а мы делаем запрос с limit = 1, то фильм не выгрузится.  Так как getTheBestFilms(limit) вернет только одну запись (1-ю позицию).

2022-11-23 12:12 UTC, DanielSJavaDev commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +            top = getTheBestFilms(limit).stream()
Ты превратно понимаешь наши с тобой роли в этом проекте :D Мы в одной команде разработчиков, реализующие "хотелки" заказчика, а заказчик хочет, чтобы топ 10 был пустым, если в нём нет фильмов 2000 года выпуска(это прописано в документации и бизнес логике, в коммерческой разработке она проверяется постман коллекциями) если тесты прошли, значит моё решение полностью удовлетворяет потребностям бизнеса, а задача команды на ревью - выявить возможные баги в реализации, чтобы не залить в прод кривой код, чтобы этот самый прод не уронить. И ещё один момент из коммерческой разработки - если можно сделать просто, значит так и делай, усложнять жизнь разработчиков дело заказчика)))

2022-11-23 12:18 UTC, AlexandrShusharin commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +            top = getTheBestFilms(limit).stream()
По итогу остались при своих ))

2022-11-23 12:19 UTC, AlexandrShusharin approved these changes

2022-11-23 12:58 UTC, alishka3d approved these changes

2022-11-23 18:14 UTC, Politik0 approved these changes

2022-11-26 15:27 UTC, alishka3d approved these changes

2022-11-27 19:10 UTC, merged