Добавление режиссёров в фильмы
AAsadova34/java-filmorate pull request #9
Opened 2022-11-22 16:51 UTC by AlexandrShusharin

2022-11-22 22:48 UTC, DanielSJavaDev commented on src/main/java/ru/yandex/practicum/filmorate/controller/DirectorController.java
> +        return directorService.getDirectors();
ты тут гетдиректорс два раза вызываешь, так было задумано или можно обойтись одним вызовом?))

2022-11-22 22:57 UTC, DanielSJavaDev commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +                    .sorted(Comparator.comparing(o->o.getReleaseDate()))
Тут можно обойтись одним листом, но это на функциональность не влияет, скорее коммент на будущий рефакторинг. В начале можно просто объявить List<Film> directorFilms; а уже в условиях заполнить лист через стрим List<Film> directorFilms = filmStorage.getListOfDirectorFilms(filmId).stream()......

2022-11-22 23:06 UTC, DanielSJavaDev commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/FilmDbStorage.java
> +        directorStorage.getDirectorById(directorId);
List<Film> films; и directorStorage.getDirectorById(directorId); тут выполняют какие-то функции или можно будет убрать на рефакторинге?)

2022-11-22 23:08 UTC, DanielSJavaDev approved these changes

2022-11-23 05:30 UTC, AAsadova34 requested changes
Все хорошо, но если я не ошиблась, то метод getListOfDirectors(long id) в классе FilmDirectorLineDbStorage нужно поправить, влияет на функционал.

2022-11-23 05:30 UTC, AAsadova34 commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    @GetMapping("/director/{id}") //получить список из первых count фильмов по количеству лайков
Комментарий не соответствует функционалу метода

2022-11-23 05:30 UTC, AAsadova34 commented on src/main/java/ru/yandex/practicum/filmorate/storage/dal/DirectorStorage.java
> +    List<Director> getListOfFilmDirectors(Long filmId);
А зачем здесь в (Long filmId) используется обертка вместо примитива?

2022-11-23 05:30 UTC, AAsadova34 commented on src/main/java/ru/yandex/practicum/filmorate/storage/dal/FilmStorage.java
> +    List<Film> getListOfDirectorFilms(Long directorId);
И здесь тоже (Long directorId)

2022-11-23 05:30 UTC, AAsadova34 commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/DirectorDbStorage.java
> +            throw new ObjectNotFoundException(String.format("Film with id %s not found", directorId));
Текст exception про фильм, а не найден режиссер

2022-11-23 05:30 UTC, AAsadova34 commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/FilmDirectorLineDbStorage.java
> +        String sqlQuery = "select GENRE_ID from film_director_line where FILM_ID = ?";
Здесь наверное не GENRE_ID, а DIRECTOR_ID?

2022-11-23 07:52 UTC, AlexandrShusharin commented on src/main/java/ru/yandex/practicum/filmorate/controller/DirectorController.java
> +        return directorService.getDirectors();
Остатки кода от процесса отладки функционала, убрал.

2022-11-23 07:52 UTC, AlexandrShusharin commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/FilmDbStorage.java
> +        directorStorage.getDirectorById(directorId);
Остатки кода от процесса отладки функционала, убрал.

2022-11-23 07:54 UTC, AlexandrShusharin commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +                    .sorted(Comparator.comparing(o->o.getReleaseDate()))
List directorFilms, убрал. Оставил
List<Film> sortedDirectorFilms = new ArrayList<>(), иначе лист будет null при невыполнении if  и else if и компилятор не пропустит.

2022-11-23 07:57 UTC, AlexandrShusharin commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/FilmDirectorLineDbStorage.java
> +        String sqlQuery = "select GENRE_ID from film_director_line where FILM_ID = ?";
Поправил, странно, что прошло тесты )

2022-11-23 07:58 UTC, AlexandrShusharin commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/DirectorDbStorage.java
> +            throw new ObjectNotFoundException(String.format("Film with id %s not found", directorId));
Поправил

2022-11-23 08:00 UTC, AlexandrShusharin commented on src/main/java/ru/yandex/practicum/filmorate/storage/dal/FilmStorage.java
> +    List<Film> getListOfDirectorFilms(Long directorId);
поправил

2022-11-23 08:00 UTC, AlexandrShusharin commented on src/main/java/ru/yandex/practicum/filmorate/storage/dal/DirectorStorage.java
> +    List<Director> getListOfFilmDirectors(Long filmId);
поправил

2022-11-23 08:01 UTC, AlexandrShusharin commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    @GetMapping("/director/{id}") //получить список из первых count фильмов по количеству лайков
поправил

2022-11-23 08:09 UTC, AlexandrShusharin commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/FilmDbStorage.java
> +        directorStorage.getDirectorById(directorId);
А нет, вру, оставил. Если не вызывать directorStorage.getDirectorById(directorId), будет возвращаться пустой список, а нужно чтобы возвращалось 404.

2022-11-23 09:46 UTC, DanielSJavaDev approved these changes

2022-11-23 15:48 UTC, Politik0 approved these changes
косметические две правки=) молодец, большую работу проделал=)

2022-11-23 15:48 UTC, Politik0 commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/DirectorDbStorage.java
> +                "WHERE film_director_line.film_id = ?";;
лишняя точка с запятой

2022-11-23 15:48 UTC, Politik0 commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/DirectorDbStorage.java
> +    }
пробела между методами не хватат

2022-11-23 16:35 UTC, AAsadova34 approved these changes
Было интересно поразбираться в твоем коде!

2022-11-23 17:14 UTC, AlexandrShusharin commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/DirectorDbStorage.java
> +                "WHERE film_director_line.film_id = ?";;
исправлено

2022-11-23 17:14 UTC, AlexandrShusharin commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/DirectorDbStorage.java
> +    }
исправлено

2022-11-23 17:42 UTC, alishka3d approved these changes

2022-11-23 17:43 UTC, alishka3d approved these changes

2022-11-23 20:45 UTC, merged